# Generated by Django 5.2.17 on 2026-09-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boss',
            name='non_recommended_attribute',
        ),
        migrations.AddField(
            model_name='boss',
            name='resistance_attribute',
            field=models.CharField(choices=[('fire', '火属性'), ('water', '水属性'), ('wind', '風属性'), ('light', '光属性'), ('dark', '闇属性'), ('earth', '地属性')], default='fire', max_length=10, verbose_name='耐性属性'),
            preserve_default=False,
        ),
    ]
