# Generated by Django 5.2.17 on 2026-09-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_remove_boss_non_recommended_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorepost',
            name='damage_stats_screenshot_url',
            field=models.URLField(default='https://example.com/temp.png', verbose_name='ダメージ統計画面のスクショURL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scorepost',
            name='screenshot_url',
            field=models.URLField(verbose_name='最終スコア画面のスクショURL'),
        ),
    ]
