# Generated by Django 5.2.17 on 2026-09-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_scorepost_damage_stats_screenshot_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorepost',
            name='badges_note',
            field=models.TextField(blank=True, verbose_name='徽章（自由記述）'),
        ),
        migrations.AddField(
            model_name='scorepost',
            name='character_1_limit_break',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='使用キャラ1の凸数'),
        ),
        migrations.AddField(
            model_name='scorepost',
            name='character_2_limit_break',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='使用キャラ2の凸数'),
        ),
        migrations.AddField(
            model_name='scorepost',
            name='character_3_limit_break',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='使用キャラ3の凸数'),
        ),
        migrations.AddField(
            model_name='scorepost',
            name='disc_note',
            field=models.TextField(blank=True, verbose_name='ロスレコ／Disc（自由記述）'),
        ),
        migrations.AddField(
            model_name='scorepost',
            name='preset_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='星ノ塔プリセットコード'),
        ),
    ]
