# Generated by Django 5.2.17 on 2026-09-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_scorepost_badges_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorepost',
            name='badges_note',
            field=models.TextField(blank=True, verbose_name='徽章（任意）'),
        ),
        migrations.AlterField(
            model_name='scorepost',
            name='character_1_limit_break',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='使用キャラ1の凸数(任意)'),
        ),
        migrations.AlterField(
            model_name='scorepost',
            name='character_2_limit_break',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='使用キャラ2の凸数(任意)'),
        ),
        migrations.AlterField(
            model_name='scorepost',
            name='character_3_limit_break',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='使用キャラ3の凸数(任意)'),
        ),
        migrations.AlterField(
            model_name='scorepost',
            name='disc_note',
            field=models.TextField(blank=True, verbose_name='ロスレコ（任意）'),
        ),
    ]
