# Generated by Django 5.2.17 on 2026-09-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_alter_scorepost_badges_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorepost',
            name='preset_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='記録プリセットコード'),
        ),
    ]
