# Generated by Django 5.2.17 on 2026-09-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_alter_scorepost_preset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorepost',
            name='preset_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='記録プリセットコード（任意）'),
        ),
    ]
