# Generated by Django 5.2.17 on 2026-09-12 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0007_alter_scorepost_preset_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='通報日時')),
                ('score_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ranking.scorepost', verbose_name='通報対象の投稿')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='通報者')),
            ],
            options={
                'verbose_name': '通報',
                'verbose_name_plural': '通報',
                'unique_together': {('user', 'score_post')},
            },
        ),
    ]
