# Generated by Django 5.2.17 on 2026-09-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0009_alter_scorepost_mvp_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorepost',
            name='mvp_slot',
            field=models.PositiveSmallIntegerField(choices=[(1, '使用キャラ1'), (2, '使用キャラ2'), (3, '使用キャラ3')], verbose_name='最多ダメージキャラ'),
        ),
    ]
