# Generated by Django 5.2.17 on 2026-09-28 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0010_alter_scorepost_mvp_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorepost',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999)], verbose_name='スコア'),
        ),
    ]
