# Generated by Django 5.2.17 on 2026-10-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0011_alter_scorepost_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(max_length=10, verbose_name='表示名（ランキングで表示される名前）'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='ユーザーID'),
        ),
    ]
